version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./dist:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"